import './globals.css'
import { Inter } from 'next/font/google'
import Topnav from '@/components/Topnav'
import Provider from '@/redux/Providers'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'tenacious',
  description: 'Generated by tenacious',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto bg-white`}>
        <Provider>
          <Topnav />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
